#ifndef _DEPLOY_CI_CLOUD_VERSION_H__
#define _DEPLOY_CI_CLOUD_VERSION_H__

#define DEPLOY_CI_CLOUD_MAJOR_VERSION 1
#define DEPLOY_CI_CLOUD_MINOR_VERSION 1
#define DEPLOY_CI_CLOUD_PATCH_VERSION 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define DEPLOY_CI_CLOUD_STRING TOSTRING(DEPLOY_CI_CLOUD_MAJOR_VERSION) "." \
                                    TOSTRING(DEPLOY_CI_CLOUD_MINOR_VERSION) "." \
                                    TOSTRING(DEPLOY_CI_CLOUD_PATCH_VERSION) " "

#endif
